# Generated by Django 5.0.14 on 2026-08-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_listing_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="payment_gateway",
            field=models.CharField(
                choices=[("NONE", "None"), ("KHALTI", "Khalti"), ("ESEWA", "eSewa")],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Stores transaction_uuid for eSewa or pidx for Khalti.",
                max_length=255,
                null=True,
            ),
        ),
    ]
