# Generated by Django 5.2.16 on 2026-07-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('region', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Terai', 'Terai'), ('Hill', 'Hill'), ('Mountain', 'Mountain')], default='Kathmandu', max_length=50)),
                ('district', models.CharField(default='Kathmandu', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=150)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_trend_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_registered', models.DateField()),
                ('market_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='market_prices.marketorigin')),
            ],
            options={
                'ordering': ['-date_registered', 'crop_name'],
                'unique_together': {('crop_name', 'market_origin', 'date_registered')},
            },
        ),
    ]
