# Generated by Django 5.2.16 on 2026-07-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('gateway', models.CharField(choices=[('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('STRIPE', 'Stripe'), ('COD', 'Cash on Delivery')], default='ESEWA', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_successful', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
